// Bundles each entry point into one self-contained file in bin/, so the plugin runs from a plain
// git checkout with no npm install. bin/ is committed; CI rebuilds and fails if it is stale.
import { build } from "esbuild";

const entries = {
  "harness-doctor": "src/cli/harness-doctor.ts",
  "harness-emit": "src/cli/harness-emit.ts",
  "harness-eval": "src/cli/harness-eval.ts",
  "harness-forget": "src/cli/harness-forget.ts",
  "harness-git-hook": "src/cli/harness-git-hook.ts",
  "harness-init": "src/cli/harness-init.ts",
  "hook-pre-tool-use": "src/hooks/pre-tool-use.ts",
  "hook-session-start": "src/hooks/session-start.ts",
  "hook-subagent-start": "src/hooks/subagent-start.ts",
  "hook-subagent-stop": "src/hooks/subagent-stop.ts",
};

await build({
  entryPoints: entries,
  outdir: "bin",
  outExtension: { ".js": ".mjs" },
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  legalComments: "none",
  logLevel: "warning",
  // The yaml package is CommonJS and requires Node built-ins; an ESM bundle has no `require`
  // unless we create one, and without it every script crashes on start.
  banner: {
    js: [
      "// Generated by scripts/build.mjs from src/. Do not edit.",
      'import { createRequire as __harnessCreateRequire } from "node:module";',
      "const require = __harnessCreateRequire(import.meta.url);",
    ].join("\n"),
  },
});
console.log(`built ${Object.keys(entries).length} scripts into bin/`);
